
const OPERATION_ACTION_ADD = "OPERATION_ACTION_ADD";
const OPERATION_ACTION_DELETE = "OPERATION_ACTION_DELETE";
const OPERATION_ACTION_UPDATE = "OPERATION_ACTION_UPDATE";
const OPERATION_ACTION_CANCEL = "OPERATION_ACTION_CANCEL";
const GET_HISTORY_OPERATION = "GET_HISTORY_OPERATION";
const FUNCTION_TYPE_PRODUCT = "FUNCTION_TYPE_PRODUCT";
const FUNCTION_TYPE_INVENTORY = "FUNCTION_TYPE_INVENTORY";
const FUNCTION_TYPE_CATEGORY_PRODUCT = "FUNCTION_TYPE_CATEGORY_PRODUCT";
const FUNCTION_TYPE_CATEGORY_POST = "FUNCTION_TYPE_CATEGORY_POST";
const FUNCTION_TYPE_ORDER = "FUNCTION_TYPE_ORDER";
const FUNCTION_TYPE_THEME = "FUNCTION_TYPE_THEME";
const FUNCTION_TYPE_PROMOTION = "FUNCTION_TYPE_PROMOTION";
