const USER_TOKEN = "USER_TOKEN";
const CURRENT_STORE_CODE = "CURRENT_STORE_CODE";
const CURRENT_USER_ID = "CURRENT_USER_ID";
const NAME_BRANCH = "NAME_BRANCH";
const LIST_FUNCTION = "LIST_FUNCTION";
const ID_BRANCH = "ID_BRANCH";
const IS_FULL_ORDER = "IS_FULL_ORDER";
const LIST_DEVICE_IP = "LIST_DEVICE_IP";
const CURRENT_DATA_STATUS = "CURRENT_DATA_STATUS";
const IS_RELEASE = "IS_RELEASE";
const IS_PRINT = "IS_PRINT";


