enum TYPE_POPUP {
  LINK,
  PRODUCT,
  CATEGORY_PRODUCT,
  CATEGORY_POST,
  POST,
}

final Map typeActionPopup = {
  TYPE_POPUP.LINK: "LINK",
  TYPE_POPUP.PRODUCT: "PRODUCT",
  TYPE_POPUP.CATEGORY_PRODUCT: "CATEGORY_PRODUCT",
  TYPE_POPUP.CATEGORY_POST: "CATEGORY_POST",
  TYPE_POPUP.POST: "POST",
};
