name: com.ikitech.store

description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.4+28

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  sahashop_customer:
    path: ./dist/doapp_customer/


  # Xep    A - Z

  add_to_cart_animation: ^1.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  bubble: ^1.2.1
  badges: ^3.1.1
  barcode: ^2.2.3
  barcode_widget: ^2.0.3
  barcode_image: ^2.0.1
  cupertino_icons: ^1.0.2
  custom_timer: ^0.1.1
  cached_network_image: ^3.1.0
  comment_tree: ^0.3.0
  carousel_slider: ^4.0.0-nullsafety.0
  collection: ^1.15.0-nullsafety.4
  connectivity_plus: 3.0.4
  #cloud_firestore: ^3.1.18
  dio: ^5.0.0
  dropdown_below: ^1.0.0
  device_info: ^2.0.0
  dotted_border: ^2.0.0+2
  direct_select_flutter: ^1.1.1
  empty_widget: ^0.0.1
  expandable: ^5.0.1
  expandable_widgets: ^1.0.3+1
  #esc_pos_utils: ^1.1.0
  #esc_pos_printer: ^4.1.0
  multi_image_picker2: ^5.0.2
  marquee_widget: ^1.2.0
  numberpicker: ^2.1.1
  network_info_plus: ^3.0.1
  flash: ^3.0.5+1
  #flutter_webrtc: ^0.8.10
  file_selector: ^0.9.2+2
  #flutter_math_fork: ^0.6.3+1
  flutter_barcode_scanner: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_image_compress: ^1.1.3
  flutter_chips_input: ^2.0.0
  flutter_svg: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_colorpicker: ^1.0.3
  flutter_datetime_picker_plus: ^2.0.1
  flutter_slidable: ^2.0.0
  firebase_messaging: ^14.1.0
  firebase_core: ^2.8.0
  flutter_speed_dial: ^6.2.0
  flutter_chat_types: ^3.0.0
  flutter_linkify: ^6.0.0
  fluttertoast: 8.1.2
  flutter_rating_bar: ^4.0.1
  flutter_chat_ui: ^1.6.9
  flutter_easyloading: ^3.0.3
  flutter_expandable_table: ^2.0.1
  #flutter_esc_pos_network: ^1.0.2
  flutter_esc_pos_utils: ^1.0.0
  #flutter_app_version_checker: ^0.3.2
  flutter_web_auth: ^0.5.0
  flutter_html: ^3.0.0-alpha.6
  flutter_widget_from_html: ^0.10.0
  flutter_parsed_text: ^2.2.1
  #flutter_widget_to_image: ^0.0.1
  font_awesome_flutter: ^10.0.0
  #html_editor_enhanced: 2.5.1
  http_parser: ^4.0.0
  hive: ^2.0.5
  hive_generator: ^2.0.0
  get: ^4.6.1
  grouped_list: ^5.1.2
  google_fonts: 4.0.4
  gallery_saver: ^2.3.2
  screenshot: ^2.1.0
  shared_preferences: ^2.0.13
  socket_io_client: ^2.0.0
  shimmer: ^2.0.0
  switcher_button: ^0.0.3
  sticky_headers: ^0.3.0+2
  sentry_flutter: ^7.8.0
  syncfusion_flutter_charts: ^23.1.36
  syncfusion_flutter_datepicker: ^23.1.36
  tiengviet: ^0.5.0
  image_picker: ^0.8.1+3
  intl: ^0.18.0
  ionicons: ^0.2.1
  image_cropper: ^3.0.1
  qr_code_scanner: ^1.0.0
  open_file_plus: ^3.3.0
  printing: ^5.10.3
  page_indicator: ^0.4.1
  pattern_formatter: ^3.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^6.0.0
  permission_handler: ^10.4.3
  pin_code_fields: ^7.2.0
  path_provider: ^2.0.1
  pull_to_refresh: ^2.0.0
  photo_view: ^0.14.0
  package_info: ^2.0.2
  pdf: ^3.1.0
  ping_discover_network_forked: ^0.0.1
  flutter_inappwebview: ^5.8.0
  retrofit: ^4.0.1
  reorderables: ^0.5.1
  readmore: ^2.2.0
  url_launcher: ^6.0.4
  youtube_player_flutter: ^8.1.0
  version_check: ^0.3.0
  flutter_fortune_wheel: ^1.3.0
  shake: ^2.2.0
  card_swiper: ^2.0.4
  after_layout: ^1.2.0
  file: ^6.1.4
  html: ^0.15.2
  video_compress: ^3.1.2
  qr_flutter: ^4.1.0
  quill_html_editor: ^2.1.9
  android_intent_plus: ^4.0.2
  flutter_app_badger: ^1.5.0
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  device_info_plus: ^8.2.2
  http: ^0.13.6
  bluetooth_print: ^4.3.0
  appsflyer_sdk: ^6.12.2
 


dev_dependencies:

  retrofit_generator: ^7.0.8
  build_runner: ^2.0.4
  change_app_package_name: ^1.0.0

  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  file_picker: ^5.2.2
  just_audio: ^0.9.30
  package_info_plus: ^3.1.2


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_ios.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/logo_ios.png"
  adaptive_icon_foreground: "assets/logo_ios.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/logo_ios.png
    - assets/barcode.png
    - assets/images/
    - assets/config/
    - assets/icons/
    - assets/image_default/
    - assets/icons/settings/
    - assets/fonts/roboto_regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # ikitech:
  fonts:
    - family: baloo2
      fonts:
        - asset: assets/fonts/baloo2.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
assets/app_user/svg/config/main_component:
  svg:
