// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPs6vNq3x70dXgvNH4EWkJ0OMMq4zkYyc',
    appId: '1:440764298359:android:7d27ccf2dfca9532104272',
    messagingSenderId: '440764298359',
    projectId: 'doapp-6413c',
    storageBucket: 'doapp-6413c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGksf_bDiROQ-xp_KG-Dq_gYCXThXjzqM',
    appId: '1:440764298359:ios:4a9a24a7529c47d1104272',
    messagingSenderId: '440764298359',
    projectId: 'doapp-6413c',
    storageBucket: 'doapp-6413c.appspot.com',
    iosClientId: '440764298359-bgvatjhifoukf9bkfi7pd0he209sqbss.apps.googleusercontent.com',
    iosBundleId: 'com.ikitech.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGksf_bDiROQ-xp_KG-Dq_gYCXThXjzqM',
    appId: '1:440764298359:ios:4a9a24a7529c47d1104272',
    messagingSenderId: '440764298359',
    projectId: 'doapp-6413c',
    storageBucket: 'doapp-6413c.appspot.com',
    iosClientId: '440764298359-bgvatjhifoukf9bkfi7pd0he209sqbss.apps.googleusercontent.com',
    iosBundleId: 'com.ikitech.store',
  );
}
